kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64
steps:
- name: test
  image: python:3-alpine
  commands:
  - apk add make
  - python3 -m pip install -r requirements-dev.txt
  - make check-lint
  - make mypy
  - make test
