name: ci

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: pwd ls
        run: |
          pwd
          ls -Al

      - name: install python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: install ffmpeg
        run: sudo apt update && sudo  apt install --yes ffmpeg

      - name: lint
        run: make lint

      - name: test
        run: make test

  publish:
    name: push to dockerhub
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tandav/musictools:latest

  deploy:
    name: deploy to server
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - run: 'curl -X POST -H "token: ${{ secrets.RESTART_HOOK_TOKEN }}" ${{ secrets.RESTART_HOOK_URL }}'


  publish-stream:
    name: build and publish stream
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile-stream
          tags: tandav/musictools-stream
