name: ci

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: pwd ls
        run: |
          pwd
          ls -Al

      - name: install ffmpeg
        run: sudo apt update && sudo  apt install --yes ffmpeg libvips

      - name: install python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: lint
        run: make lint

      - name: git log messages.txt
        run: make messages

      - name: test
        run: make test

  publish:
    name: push to dockerhub
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: tandav/musictools

  deploy:
    name: deploy to server
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - run: 'curl -X POST -H "token: ${{ secrets.RESTART_HOOK_TOKEN }}" ${{ secrets.RESTART_HOOK_URL }}'


  publish-stream:
    name: build and publish stream
    runs-on: ubuntu-latest
    needs: test

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Build and push Docker images
#        run: make build_push_streaming

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          file: Dockerfile-stream
          tags: tandav/musictools-stream
